server:
  port: 8081
  tomcat:
    socket-options:
      soLinger: -1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_mds
    username: mds_user
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
